-- 0016_catalog_rebalance.sql
-- Bußgeldkatalog neu ausbalanciert (min-max Fine + HE, "Hart"-Staffel, Cap 45/60).
-- Baut catalog_entries komplett aus public/bussgeldkatalog.js neu auf.

DELETE FROM catalog_entries;

INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§13 Abs. 1', 'Raub', '$6.000 - $10.000', '15 - 25', NULL, 0);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§13 Abs. 2', 'Raub in besonders schweren Fall', '$10.000 - $16.000', '25 - 40', NULL, 1);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§14 Abs. 1', 'Erpressung', '$5.000 - $9.000', '12 - 20', NULL, 2);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§15 Abs. 1', 'Betrug', '$4.000 - $8.000', '8 - 15', NULL, 3);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§16 Abs. 1', 'Leichte Körperverletzung', '$800 - $1.800', '2 - 5', NULL, 4);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§16 Abs. 2', 'Gefährliche Körperverletzung', '$3.000 - $6.000', '8 - 15', NULL, 5);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§16 Abs. 3', 'Schwere Körperverletzung', '$6.000 - $11.000', '15 - 25', NULL, 6);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§16 Abs. 4', 'Fahrlässige Körperverletzung', '$1.500 - $3.000', '3 - 8', NULL, 7);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§17 Abs. 1', 'Versuchter Mord', '$10.000 - $16.000', '30 - 45', NULL, 8);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§17 Abs. 2', 'Mehrfach versuchter Mord / besondere Schwere der Tat', '$16.000 - $25.000', '40 - 60', NULL, 9);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§18 Abs. 1', 'Freiheitsentzug', '$5.000 - $9.000', '10 - 20', NULL, 10);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§19 Abs. 1', 'Verfassungswidrige Handlung', '$12.000 - $20.000', '25 - 45', NULL, 11);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§20 Abs. 1', 'Beweismittelfälschung', '$3.000 - $6.000', '8 - 15', NULL, 12);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§21 Abs. 1', 'Falsche Beweisaussage', '$3.000 - $6.000', '8 - 15', NULL, 13);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§21 Abs. 2', 'Meineid', '$4.000 - $7.000', '10 - 18', NULL, 14);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§22 Abs. 1', 'Entweichung von Gefangenen', 'doppelte reguläre Haftzeit und Geldstrafe', '-', NULL, 15);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§23 Abs. 1', 'Beihilfe zum Gefängnisausbruch', '$4.000 - $8.000', '10 - 20', NULL, 16);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§24 Abs. 1', 'Strafvereitelung', '$3.000 - $6.000', '8 - 15', NULL, 17);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§25 Abs. 1', 'Geiselnahme', '$8.000 - $14.000', '25 - 45', NULL, 18);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§26 Abs. 1', 'Widerstand gegen Vollstreckungsbeamte', '$1.500 - $3.500', '3 - 8', NULL, 19);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§27 Abs. 2', 'Widerstand gegen Anweisungen', '$500 - $1.200', '1 - 3', NULL, 20);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§28 Abs. 1', 'Unbefugtes Betreten von Speerbezirken', '$400 - $1.000', '1 - 3', 'evtl. Platzverweis sollte die Person diesem nicht nachkommen = Haftzeit', 21);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§29 Abs. 1', 'Hehlerei', '$2.000 - $5.000', '5 - 12', NULL, 22);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§30 Abs. 1', 'Brandstiftung', '$6.000 - $12.000', '15 - 30', 'Aufkommen für den Sachschaden', 23);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StGb', '§31 Abs. 1', 'Nachstellung / Belästigung', '$600 - $1.500', '2 - 5', NULL, 24);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 1', 'WaffG Straftaten / widersetzen des Waffenverbotes', '$2.500 - $5.000', '10 - 20', 'Waffe/n einziehen', 0);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 2', 'WaffG Straftaten / widersetzen der Entwaffnung', '$3.000 - $6.000', '10 - 20', 'Waffe/n einziehen', 1);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 3', 'Illegaler Waffenbesitz A', '$3.000 - $6.000', '12 - 20', 'Waffe/n einziehen', 2);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 4', 'Illegaler Waffenhandel A', '$8.000 - $14.000', '20 - 30', 'Waffe/n einziehen', 3);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 5', 'Illegaler Waffenbesitz B', '$5.000 - $9.000', '15 - 25', 'Waffe/n einziehen', 4);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 6', 'Illegaler Waffenhandel B', '$11.000 - $18.000', '25 - 35', 'Waffe/n einziehen', 5);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 7', 'Illegaler Waffenbesitz C', '$7.000 - $12.000', '18 - 28', 'Waffe/n einziehen', 6);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 8', 'Illegaler Waffenhandel C', '$14.000 - $23.000', '30 - 40', 'Waffe/n einziehen', 7);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 10', 'Illegaler Waffenbesitz D', '$9.000 - $16.000', '20 - 32', 'Waffe/n einziehen', 8);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 11', 'Illegaler Waffenhandel D', '$18.000 - $30.000', '35 - 45', 'Waffe/n einziehen', 9);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§15 Abs. 9', 'WaffG Straftaten / Zweckentfremdung der Waffenscheine', '$5.000 - $9.000', '12 - 20', NULL, 10);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§16 Abs. 1', 'Waffenteile', '$2.000 - $4.000', '8 - 15', 'Waffenteile einziehen', 11);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('WaffG', '§17 Abs. 6', 'WaffG Waffenscheininhaber / Verwenden einer Schusswaffe außerhalb der Schießstätte', '$3.000 - $6.000', '10 - 18', 'Waffenschein einziehen', 12);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('BtmG', '§7 Abs. 1a', 'Handel mit Betäubungsmitteln', '$6.000 - $12.000', '15 - 30', 'zzgl. $500 Aufschlag pro Drogeneinheit', 0);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('BtmG', '§7 Abs. 1b', 'Wer für Betäubungsmittel wirbt', '$2.000 - $4.000', '3 - 8', NULL, 1);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('BtmG', '§7 Abs. 1c', 'Falsche Angaben um an eine Verschreibung für Btm zu kommen', '$2.500 - $5.000', '3 - 8', NULL, 2);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('BtmG', '§7 Abs. 1d', 'Besitz von Btm über dem Eigenbedarf', '$1.500 - $3.500', '2 - 6', NULL, 3);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§2 Abs. 1', 'Fahren abseits befestigter Strassen', '$80 - $200', '-', NULL, 0);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§3 Abs. 1', 'Überschreiten der Höchstgeschw. 5-20 kmh', '$50 - $150', '-', NULL, 1);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§3 Abs. 1', 'Überschreiten der Höchstgeschw. 20-50 kmh', '$120 - $300', '-', NULL, 2);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§3 Abs. 1', 'Überschreiten der Höchstgeschw. 50-100 kmh', '$250 - $500', '-', NULL, 3);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§3 Abs. 1', 'Überschreiten der Höchstgeschw. 100+ kmh', '$400 - $800', '-', NULL, 4);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§3 Abs. 1', 'Überschreiten der Höchstgeschw.100+ kmh außerorts', '$350 - $700', '-', NULL, 5);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§4 Abs. 1', 'Missachten der Vorfahrt', '$150 - $350', '-', NULL, 6);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§4 Abs. 2', 'Missachten der Verkehrszeichen', '$150 - $350', '-', NULL, 7);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§5 Abs. 1', 'Abstand zu gering', '$120 - $300', '-', NULL, 8);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§6 Abs. 2', 'Überhol. der den Verkehr gefärdet', '$300 - $600', '-', 'evtl. Führerschein entzug', 9);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§6 Abs. 3', 'Nicht ausreich. Mindestabstand beim Überhol.', '$180 - $400', '-', NULL, 10);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§7 Abs. 1-2', 'Fahren ohne Licht', '$75 - $200', '-', NULL, 11);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§8 Abs. 1', 'Missbrauch von Signaleinrichtung', '$300 - $600', '-', NULL, 12);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§9 Abs. 1-4', 'Unzulässiges Halten und Parken', '$150 - $400', '-', 'evtl. Abschleppen', 13);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§10 Abs. 1', 'Fahren ohne Warnw. Verband. und Warndreieck', '$100 - $250', '-', NULL, 14);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§11 Abs. 1', 'Widerstand gegen Weisungen der Exekutive', '$300 - $700', '1 - 3', NULL, 15);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§12 Abs. 1', 'Das Fahren ohne Fahrerlaubnis', '$500 - $1.200', '1 - 3', NULL, 16);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§14 Abs. 2', 'Verstoß Rechtsfahrgebot', '$120 - $300', '-', NULL, 17);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§15 Abs. 1-2', 'Gefährliches Fahrverhalten', '$600 - $1.500', '1 - 3', 'evtl. Führerschein entzug', 18);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§16 Abs. 1', 'Verkehsbehinderung', '$150 - $400', '-', NULL, 19);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§18 Abs. 1', 'Fahren ohne Schutzhelm', '$50 - $150', '-', NULL, 20);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§19 Abs. 1', 'Fahrerflucht', '$600 - $1.500', '2 - 5', NULL, 21);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('StVO', '§21 Abs.', 'Illegales Tuning', '$700 - $1.800', '-', 'Ausbau des illegalen Tunings', 22);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§2 Abs. 1 & 2', 'Mindestflughöhe und Sicherheitsabstand', '$300 - $700', '-', '-', 0);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§3 Abs. 1', 'unangemessene Fluggeschwindigkeit', '$400 - $800', '-', '-', 1);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§4 Abs. 1', 'unzulässiges Landen', '$600 - $1.200', '-', '-', 2);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§5 Abs. 1', 'Fliegen unter Alkohol, Drogen', '$800 - $1.800', '2 - 5', '-', 3);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§7 Abs. 1', 'Widerstand gegen Weisungen der Exekutive', '$500 - $1.000', '-', '-', 4);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§8 Abs. 1', 'Fliegen ohne Fluglizenz', '$900 - $2.000', '-', NULL, 5);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§8 Abs. 2', 'Missachtung der LVO im schweren Fall', '-', '-', 'Entzug der Fluglizenz', 6);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§9 Abs. 1', 'Gefährliches Flugverhalten', '$700 - $1.500', '-', '-', 7);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§9 Abs. 1', 'Gefährliches Flugverhalten mit Gefährdung', '$900 - $2.000', '-', '-', 8);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§10', 'Fliegen in einer Flugverbotszone', '$800 - $1.800', '-', 'Entzug der Fluglizenz', 9);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('LVO', '§11', 'Fallschirmspringen in Flugverbotszone, etc.', '$500 - $1.000', '-', '-', 10);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('UZwGE', '§9 Abs. 3.1', 'Einsatzkosten I', '$800 - $1.500', '-', NULL, 0);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('UZwGE', '§9 Abs. 3.2', 'Einsatzkosten II', '$1.500 - $2.500', '-', NULL, 1);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('UZwGE', '§9 Abs. 3.3', 'Einsatzkosten III', '$2.500 - $3.800', '-', NULL, 2);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('UZwGE', '§9 Abs. 3.4', 'Einsatzkosten IV', '$3.000 - $5.000', '-', NULL, 3);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§3 Abs. 1', 'Sachbeschädigung', '$300 - $900', '-', 'muss für entstandenen Sachschaden aufkommen', 0);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§4 Abs. 1', 'Beleidigung', '$200 - $600', '-', NULL, 1);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§5 Abs. 1', 'Missbräuchlicher Dispatch', '$500 - $1.200', '-', 'Kosten für den Einsatz müssen übernommen werden
bei wiederholter Tat bis zu $5.000', 2);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§6 Abs. 1', 'Erregung öffentlichen Ärgernisses', '$200 - $500', '-', NULL, 3);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§7 Abs. 1', 'Verbotene Ausübung der Prostitution', '$600 - $1.500', '-', NULL, 4);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§8 Abs. 1', 'Identität kann nicht festgestellt werden', '$300 - $800', '-', NULL, 5);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§9 Abs. 1', 'Unrichtige Angabe oder Angabe verweigert bzgl. 
Vor-, Familien- oder Geburtsnamen, den Ort oder Tag seiner Geburt, seinen Familienstand,
seinen Beruf, seinen Wohnort, seine Wohnung oder seine Staatsangehörigkeit', '$400 - $1.000', '-', 'Wenn nicht nach anderen Vorschriften geahndet werden kann', 6);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§10 Abs. 1', 'Tierquälerei', '$500 - $1.500', '-', NULL, 7);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§11', 'nicht genehmigter Protest', '$600 - $1.500', '-', NULL, 8);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§12 Abs. 1', 'Unzulässiger Lärm', '$150 - $400', '-', 'Wenn nicht nach anderen Vorschriften geahndet werden kann', 9);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§13 Abs. 1', 'Belästigung der Allgemeinheit', '$250 - $600', '-', 'Wenn nicht nach anderen Vorschriften geahndet werden kann', 10);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§14', 'Verschmutzung der Umwelt', '$300 - $1.500', '-', NULL, 11);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§15', 'Anordnung auf Erzwingungshaft', '-', 'pro $500 Ordnungsgeld = 1 HE', NULL, 12);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§16 Abs. 1', 'Üble Nachrede', '$300 - $800', '-', NULL, 13);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§17 Abs. 1', 'Diebstahl', '$1.200 - $2.500', '5 - 12', NULL, 14);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§17 Abs. 2', 'Diebstahl in besonders schwerem Fall', '$2.500 - $4.500', '10 - 20', NULL, 15);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§18 Abs. 1', 'Dokumentenfälschung', '$2.000 - $4.000', '5 - 12', NULL, 16);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§18 Abs. 2', 'Dokumentenfälschung / Schwarzgeld', '$3.000 - $6.000', '8 - 15', NULL, 17);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§19 Abs. 1-2', 'Glücksspiel', '$500 - $1.200', '1 - 3', NULL, 18);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§20 Abs. 1', 'Amtsanmaßung', '$2.500 - $5.000', '8 - 15', NULL, 19);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§21 Abs. 1', 'Behinderung der Justiz', '$1.500 - $3.500', '3 - 8', NULL, 20);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§22 Abs. 1', 'Behinderung der Behördenarbeit', '$1.500 - $3.500', '3 - 8', NULL, 21);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§23 Abs. 1', 'Drohung', '$1.500 - $3.500', '5 - 10', NULL, 22);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§24 Abs. 1', 'Hausfriedensbruch', '$1.000 - $2.500', '2 - 6', NULL, 23);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('OWiG', '§25 Abs. 1', 'Vermummungsverbot in bestimmten Räumlichkeiten', '$600 - $1.500', '1 - 3', NULL, 24);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§1 Abs. 1', 'Bestechung', '$8.000 - $15.000', '15 - 30', NULL, 0);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§2 Abs. 1', 'Bestechlichkeit', '$8.000 - $15.000', '15 - 30', NULL, 1);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§2 Abs. 1.1', 'Bestechlichkeit / nach Verlassen des Dienstes', '$6.000 - $10.000', '15 - 30', NULL, 2);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§3 Abs. 1', 'Vorteilsgewährung', '$6.000 - $12.000', '12 - 25', NULL, 3);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§4 Abs. 1', 'Vorteilsannahme', '$6.000 - $12.000', '12 - 25', NULL, 4);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§4 Abs. 1.1', 'Vorteilsannahme / nach Verlassen des Dienstes', '$5.000 - $9.000', '12 - 25', NULL, 5);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§5 Abs. 1', 'Rechtsbeugung', '$10.000 - $18.000', '20 - 35', 'kann bis zu 3 Tage vom Dienst suspendiert werden', 6);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§6 Abs. 1', 'Aussageerpressung', '$14.000 - $22.000', '40 - 60', NULL, 7);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§6 Abs. 2', 'Aussageerpressung / minder schwerer Fall', '$8.000 - $14.000', '15 - 30', NULL, 8);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§7 Abs. 1', 'Verfolgung Unschuldiger', '$12.000 - $18.000', '30 - 50', NULL, 9);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§7 Abs. 1', 'Verfolgung Unschuldiger / minder schwerer Fall', '$6.000 - $10.000', '15 - 25', NULL, 10);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§7 Abs. 2', 'Verfolgung Unschuldiger / Immunität', '$10.000 - $16.000', '20 - 40', NULL, 11);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§8 Abs. 1', 'Vollstreckung gegen Unschuldige', '$16.000 - $24.000', '30 - 50', NULL, 12);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§8 Abs. 1', 'Vollstreckung gegen Unschuldige / minder schwerer Fall', '$10.000 - $16.000', '15 - 25', NULL, 13);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§8 Abs. 2', 'Vollstreckung gegen Unschuldige / leichtfertig', '$8.000 - $12.000', '10 - 20', NULL, 14);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§8 Abs. 3', 'Vollstreckung gegen Unschuldige / Fälle abgesehen von Abs. 1', '$14.000 - $20.000', '25 - 50', NULL, 15);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§9 Abs. 1', 'Falschbeurkundung beim Amt', '$6.000 - $10.000', '10 - 20', NULL, 16);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§10 Abs. 1', 'Amtsmissbrauch', '$12.000 - $18.000', '30 - 60', NULL, 17);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§10 Abs. 3', 'Herausgabe von Informationen oder Dienstequipment', '$10.000 - $16.000', '50 - 60', NULL, 18);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§10 Abs. 3', 'Fahrlässige Herausgabe von Informationen', '$5.000 - $9.000', '15 - 30', NULL, 19);
INSERT INTO catalog_entries (code, paragraph, bedeutung, strafe, he, sonstiges, position) VALUES ('AkG', '§10 Abs. 5', 'Amtsgewaltsmittbrauch', '$12.000 - $18.000', '30 - 60', NULL, 20);
